"""
Генерирует текстовое представление графа зависимостей в формате D2 и
показывает ASCII-дерево (если передан флаг --ascii).
Также демонстрация примеров визуализации для трёх пакетов (если они есть в тестовом файле).
"""

import argparse
import os
import sys
from collections import defaultdict

def validate_path(value):
    if os.path.exists(value):
        return os.path.abspath(value)
    raise argparse.ArgumentTypeError("Укажите существующий путь к тестовому файлу")

def parse_args():
    p = argparse.ArgumentParser(description="Stage 5: Visualization to D2 and ASCII tree")
    p.add_argument("--repo", "-r", required=True, type=validate_path)
    p.add_argument("--packages", "-p", nargs="*", default=[], help="Список пакетов для визуализации (если пустой — попытаемся взять 3 первых)")
    p.add_argument("--ascii", action="store_true", help="Показать зависимости в ASCII-дереве")
    p.add_argument("--max-depth", type=int, default=10)
    p.add_argument("--filter", default="")
    return p.parse_args()

def read_test_repo(path):
    deps = {}
    with open(path, "r", encoding="utf-8") as f:
        for raw in f:
            line = raw.strip()
            if not line or line.startswith("#"):
                continue
            if ":" not in line:
                continue
            left, right = line.split(":", 1)
            pkg = left.strip()
            dep_list = [x for x in (right.strip().split()) if x]
            deps[pkg] = dep_list
    return deps

def build_transitive(repo_map, start, max_depth, exclude_substr):
    from collections import deque
    graph = defaultdict(list)
    visited = set([start])
    q = deque([(start, 0)])
    while q:
        node, depth = q.popleft()
        if depth >= max_depth:
            continue
        for nb in repo_map.get(node, []):
            if exclude_substr and exclude_substr in nb:
                continue
            graph[node].append(nb)
            if nb not in visited:
                visited.add(nb)
                q.append((nb, depth+1))
    return graph

def generate_d2(graph, root_name):
    """
    Простой генератор D2: узлы и связи в текстовом виде.
    Пример вывода:
    A -> B
    A -> C
    """
    lines = []
    nodes = set()
    for a, neigh in graph.items():
        nodes.add(a)
        for b in neigh:
            nodes.add(b)
            lines.append(f'{a} -> {b}')
    header = "// D2 graph generated by stage5\n\n"
    body = "\n".join(lines)
    return header + body

def ascii_tree_print(graph, root, prefix="", visited=None, depth=0, max_depth=20):
    if visited is None:
        visited = set()

    # Защита от бесконечной рекурсии
    if depth > max_depth:
        print(prefix + f"{root} ... (max depth reached)")
        return

    if root in visited:
        print(prefix + f"{root} (cycle)")
        return

    visited.add(root)
    children = graph.get(root, [])

    if not children:
        print(prefix + root)
        return

    print(prefix + root)
    for i, c in enumerate(children):
        last = (i == len(children)-1)
        next_prefix = prefix + ("└─ " if last else "├─ ")
        ascii_tree_print(graph, c, prefix + ("   " if last else "│  "), visited.copy(), depth+1, max_depth)

def main():
    args = parse_args()
    repo_map = read_test_repo(args.repo)

    print(f"Загружено пакетов: {len(repo_map)}")
    print(f"Доступные пакеты: {list(repo_map.keys())[:10]}...")  # Покажем первые 10

    all_pkgs = list(repo_map.keys())
    targets = args.packages or all_pkgs[:3]

    print(f"Целевые пакеты для визуализации: {targets}")

    for t in targets:
        if t not in repo_map:
            print(f"\n[WARN] Пакет '{t}' не найден в репозитории. Пропускаем.")
            continue

        print("\n" + "="*40)
        print(f"Визуализация для пакета: {t}")

        graph = build_transitive(repo_map, t, args.max_depth, args.filter)

        if not graph:
            print(f"Граф для пакета '{t}' пуст (возможно, все зависимости отфильтрованы)")
            continue

        # Генерация D2
        d2 = generate_d2(graph, t)
        d2_file = f"d2_{t}.txt"
        with open(d2_file, "w", encoding="utf-8") as f:
            f.write(d2)
        print(f"Сформирован D2 в файле: {d2_file}")
        print("---- D2 preview (первые 20 строк) ----")
        print("\n".join(d2.split("\n")[:20]))

        # ASCII дерево
        if args.ascii:
            print("---- ASCII tree ----")
            ascii_tree_print(graph, t, max_depth=args.max_depth)

    print("\nГотово. D2-файлы созданы в текущей папке.")

if __name__ == "__main__":
    main()

# python3 config2/stage5.py --repo config2/repo.txt --packages A B AA --ascii --max-depth 6